AuthTest/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AuthTest.Data;
using AuthTest.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace AuthTest.Controllers
{
    public class ArticlesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public ArticlesController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Articles
        public async Task<IActionResult> Index()
        {
            const int summaryLength = 250;
            var articles = await _context.Articles.ToListAsync();

            foreach (var article in articles)
            {
                var shortContent = new List<string>();
                var words = article.Content.Split(' ');
                var letterCount = 0;

                foreach (var word in words)
                {
                    if (letterCount < summaryLength)
                    {
                        var currentWord = word;
                        letterCount += word.Length + 1;
                        if(letterCount >= summaryLength)
                        {
                            currentWord += "...";
                        }
                        shortContent.Add(currentWord);
                    }
                }

                article.Content = string.Join(' ', shortContent.ToArray());
            }

            return View(articles.OrderBy(s => s.CreationDate));
        }

        // GET: Articles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appArticle = await _context.Articles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (appArticle == null)
            {
                return NotFound();
            }

            return View(appArticle);
        }

        // GET: Articles/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Articles/Create
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Content")] AppArticle appArticle)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);

            appArticle.AuthorId = user.Id;
            appArticle.CreationDate = DateTime.Now;
            appArticle.LastUpdatedDate = DateTime.Now;

            //fix this
            appArticle.AuthorName = user.Email;

            if (ModelState.IsValid)
            {
                _context.Add(appArticle);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(appArticle);
        }

        // GET: Articles/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appArticle = await _context.Articles.FindAsync(id);
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var roles = await _userManager.GetRolesAsync(user);

            if (appArticle == null)
            {
                return NotFound();
            }

            if (user.Id != appArticle.AuthorId && !roles.Contains("Admin"))
            {
                return NotFound();
            }

            return View(appArticle);
        }

        // POST: Articles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,AuthorId,CreationDate,Title,Content,AuthorName")] AppArticle appArticle)
        {
            if (id != appArticle.Id)
            {
                return NotFound();
            }

            var user = await _userManager.GetUserAsync(HttpContext.User);
            var roles = await _userManager.GetRolesAsync(user);
            if(user.Id != appArticle.AuthorId && !roles.Contains("Admin"))
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    appArticle.LastUpdatedDate = DateTime.Now;
                    _context.Update(appArticle);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AppArticleExists(appArticle.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(appArticle);
        }

        // GET: Articles/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appArticle = await _context.Articles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (appArticle == null)
            {
                return NotFound();
            }

            var user = await _userManager.GetUserAsync(HttpContext.User);
            var roles = await _userManager.GetRolesAsync(user);
            if (user.Id != appArticle.AuthorId && !roles.Contains("Admin"))
            {
                return NotFound();
            }

            return View(appArticle);
        }

        // POST: Articles/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var appArticle = await _context.Articles.FindAsync(id);
            
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var roles = await _userManager.GetRolesAsync(user);
            if (user.Id != appArticle.AuthorId && !roles.Contains("Admin"))
            {
                return NotFound();
            }

            _context.Articles.Remove(appArticle);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AppArticleExists(int id)
        {
            return _context.Articles.Any(e => e.Id == id);
        }
    }
}

AuthTest/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AuthTest.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AuthTest.Controllers
{
    public class TestController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public TestController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Admin()
        {
            var users = _userManager.Users.ToList();

            return View(users);
        }
    }
}

AuthTest/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AuthTest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src='https://cdn.tiny.cloud/1/dkr7w7zlthb5wtez2ouxeo73mpsc349pgdl31o92wfz3t0ov/tinymce/5/tinymce.min.js' referrerpolicy="origin"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Kyle's Blog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Articles" asp-action="Index">Blog</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Test" asp-action="Admin">Admin</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - AuthTest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>